server {
    listen 80;
    
    # Oculta a versão do Nginx (Evita Server Leaks)
    server_tokens off;

    # Cabeçalhos de Segurança (Security Headers)
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Content-Security-Policy "default-src 'self'; connect-src 'self' http://localhost:3000; img-src 'self' data: http://localhost:3000; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline';";
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()";
    add_header Cross-Origin-Embedder-Policy "unsafe-none"; 
    add_header Cross-Origin-Opener-Policy "same-origin";
    add_header Cross-Origin-Resource-Policy "same-origin";

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
